name: hyspecppt_dev
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pyqt == 5.*
  - qtpy
  - numpy
  - scipy
  - matplotlib <3.9 #resolves pyside 6 error
  - pre-commit
  # package building:
  - versioningit
  - libmamba
  - libarchive
  - anaconda-client
  - boa
  - conda-build < 4  # conda-build 24.x has a bug, missing update_index from conda_build.index
  - conda-verify
  - python-build
  - twine  # for uploading to pypi and testpypi
  # docs
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-mermaid
  - myst-parser  # required for parsing markdown files
  # test: list all test dependencies here
  - pytest
  - pytest-qt
  - pytest-cov
  - pytest-xdist
  - pytest-xvfb
