name: unit-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]
    tags: ['v*']

jobs:
  pytest_package_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment-key: ${{ runner.os }}-env-${{ hashFiles('**/environment.yml') }}
          cache-downloads-key: ${{ runner.os }}-downloads-${{ hashFiles('**/environment.yml') }}
          condarc: |
            channels:
              - conda-forge
      - name: install in editable mode
        run: |
          echo "installing in editable mode"
          python -m pip install -e .
      - name: run unit tests
        run: |
          echo "running unit tests"
          python -m pytest --cov=src --cov-report=xml --cov-report=term-missing tests/
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v4
        if:
          github.actor != 'dependabot[bot]'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: build python wheel - pypi
        run: |
          # test that the python wheel builds
          VERSION=$(versioningit .) python -m build --wheel --no-isolation
          twine check dist/hyspecplanningtools-*.whl
      - name: build conda package
        run: |
          # test that the conda package builds
          cd conda.recipe
          echo "versioningit $(versioningit ../)"
          # conda channels could have been defined in the conda-incubator, but you can copy/paste the lines
          # below to build the conda package in your local machine
          CHANNELS="--channel conda-forge"
          VERSION=$(versioningit ../) conda mambabuild $CHANNELS --output-folder . .
          conda verify noarch/hyspecplanningtools*.tar.bz2
